original_to_safe:
  右腿大腿，最靠右侧: M_104439
  右髂嵴/PSIS区: R_PSIS
  右腿膝盖: R_KNE
  右髂前上棘: R_ASIS
  右三头肌中间: M_104557
  右手右前: M_104562
  右手肘关节: R_ELB
  右脚最前端: R_TOE
  头最右部分（耳朵上方一点）: M_104571
  右手手腕: R_WRA
  右肩峰: R_ACR
  右手右后: M_104575
  右手左前: M_104578_104641_104642_104643_104645_104646_1046
  头顶: HEAD_TOP
  右下肋缘附近点（腰）: M_104582
  左脚最前端: L_TOE
  左脚，小拇指旁: M_104591
  左腿膝盖: L_KNE
  左手右前: M_104596
  左肩峰: L_ACR
  左脚，大拇指旁: L_TOE_02
  两胸之间: STRN
  左脚脚后跟（右）: R_HEE
  左脚脚后跟（左）: L_HEE
  头最左部分（耳朵上方一点）: M_104607
  脊椎上（C7区）: C7
  右脚，大拇指旁: R_TOE_02
  左下肋缘附近点（腰）: M_104610
  左腿大腿，最靠左侧: M_104611
  右手左后: M_104613
  左手右后: M_104615
  右肩胛上区: R_SCAP_SUP
  肚子: BELL
  左三头肌中间: M_104618
  左手手腕: L_WRA
  右脚，小拇指旁: M_104622
  右肩胛下区: R_SCAP_INF
  额头上一点: HEAD_FRONT
  右脚脚后跟（左）: R_HEE_02
  右脚：脚背与小腿骨连接处: R_ANK
  右脚脚后跟（右）: R_HEE_03
  左手左后: M_104630
  左肩胛上区: L_SCAP_SUP
  左手左前: M_104632
  左手肘关节: L_ELB
  左髂嵴/PSIS区: L_PSIS
  左髂前上棘: L_ASIS
  左肩胛下区: L_SCAP_INF
  脊椎下区（略微偏左一点点）: M_104637
  左脚：脚背与小腿骨连接处: L_ANK
safe_to_original:
  M_104439: 右腿大腿，最靠右侧
  R_PSIS: 右髂嵴/PSIS区
  R_KNE: 右腿膝盖
  R_ASIS: 右髂前上棘
  M_104557: 右三头肌中间
  M_104562: 右手右前
  R_ELB: 右手肘关节
  R_TOE: 右脚最前端
  M_104571: 头最右部分（耳朵上方一点）
  R_WRA: 右手手腕
  R_ACR: 右肩峰
  M_104575: 右手右后
  M_104578_104641_104642_104643_104645_104646_1046: 右手左前
  HEAD_TOP: 头顶
  M_104582: 右下肋缘附近点（腰）
  L_TOE: 左脚最前端
  M_104591: 左脚，小拇指旁
  L_KNE: 左腿膝盖
  M_104596: 左手右前
  L_ACR: 左肩峰
  L_TOE_02: 左脚，大拇指旁
  STRN: 两胸之间
  R_HEE: 左脚脚后跟（右）
  L_HEE: 左脚脚后跟（左）
  M_104607: 头最左部分（耳朵上方一点）
  C7: 脊椎上（C7区）
  R_TOE_02: 右脚，大拇指旁
  M_104610: 左下肋缘附近点（腰）
  M_104611: 左腿大腿，最靠左侧
  M_104613: 右手左后
  M_104615: 左手右后
  R_SCAP_SUP: 右肩胛上区
  BELL: 肚子
  M_104618: 左三头肌中间
  L_WRA: 左手手腕
  M_104622: 右脚，小拇指旁
  R_SCAP_INF: 右肩胛下区
  HEAD_FRONT: 额头上一点
  R_HEE_02: 右脚脚后跟（左）
  R_ANK: 右脚：脚背与小腿骨连接处
  R_HEE_03: 右脚脚后跟（右）
  M_104630: 左手左后
  L_SCAP_SUP: 左肩胛上区
  M_104632: 左手左前
  L_ELB: 左手肘关节
  L_PSIS: 左髂嵴/PSIS区
  L_ASIS: 左髂前上棘
  L_SCAP_INF: 左肩胛下区
  M_104637: 脊椎下区（略微偏左一点点）
  L_ANK: 左脚：脚背与小腿骨连接处
markers:
- index: 0
  original_name: 右腿大腿，最靠右侧
  original_id: '104439'
  type: Marker
  safe_label: M_104439
- index: 1
  original_name: 右髂嵴/PSIS区
  original_id: '104491'
  type: Marker
  safe_label: R_PSIS
- index: 2
  original_name: 右腿膝盖
  original_id: '104519'
  type: Marker
  safe_label: R_KNE
- index: 3
  original_name: 右髂前上棘
  original_id: '104543'
  type: Marker
  safe_label: R_ASIS
- index: 4
  original_name: 右三头肌中间
  original_id: '104557'
  type: Marker
  safe_label: M_104557
- index: 5
  original_name: 右手右前
  original_id: '104562'
  type: Marker
  safe_label: M_104562
- index: 6
  original_name: 右手肘关节
  original_id: '104563'
  type: Marker
  safe_label: R_ELB
- index: 7
  original_name: 右脚最前端
  original_id: '104564'
  type: Marker
  safe_label: R_TOE
- index: 8
  original_name: 头最右部分（耳朵上方一点）
  original_id: '104571'
  type: Marker
  safe_label: M_104571
- index: 9
  original_name: 右手手腕
  original_id: '104572'
  type: Marker
  safe_label: R_WRA
- index: 10
  original_name: 右肩峰
  original_id: '104573'
  type: Marker
  safe_label: R_ACR
- index: 11
  original_name: 右手右后
  original_id: '104575'
  type: Marker
  safe_label: M_104575
- index: 12
  original_name: 右手左前
  original_id: 104578+104641+104642+104643+104645+104646+104647+104648+104649+104650+104651+104652+104653+104654+104655+104656+104657+104658+104659
  type: Marker
  safe_label: M_104578_104641_104642_104643_104645_104646_1046
- index: 13
  original_name: 头顶
  original_id: '104579'
  type: Marker
  safe_label: HEAD_TOP
- index: 14
  original_name: 右下肋缘附近点（腰）
  original_id: '104582'
  type: Marker
  safe_label: M_104582
- index: 15
  original_name: 左脚最前端
  original_id: '104584'
  type: Marker
  safe_label: L_TOE
- index: 16
  original_name: 左脚，小拇指旁
  original_id: '104591'
  type: Marker
  safe_label: M_104591
- index: 17
  original_name: 左腿膝盖
  original_id: '104594'
  type: Marker
  safe_label: L_KNE
- index: 18
  original_name: 左手右前
  original_id: '104596'
  type: Marker
  safe_label: M_104596
- index: 19
  original_name: 左肩峰
  original_id: '104600'
  type: Marker
  safe_label: L_ACR
- index: 20
  original_name: 左脚，大拇指旁
  original_id: '104602'
  type: Marker
  safe_label: L_TOE_02
- index: 21
  original_name: 两胸之间
  original_id: '104604'
  type: Marker
  safe_label: STRN
- index: 22
  original_name: 左脚脚后跟（右）
  original_id: '104605'
  type: Marker
  safe_label: R_HEE
- index: 23
  original_name: 左脚脚后跟（左）
  original_id: '104606'
  type: Marker
  safe_label: L_HEE
- index: 24
  original_name: 头最左部分（耳朵上方一点）
  original_id: '104607'
  type: Marker
  safe_label: M_104607
- index: 25
  original_name: 脊椎上（C7区）
  original_id: '104608'
  type: Marker
  safe_label: C7
- index: 26
  original_name: 右脚，大拇指旁
  original_id: '104609'
  type: Marker
  safe_label: R_TOE_02
- index: 27
  original_name: 左下肋缘附近点（腰）
  original_id: '104610'
  type: Marker
  safe_label: M_104610
- index: 28
  original_name: 左腿大腿，最靠左侧
  original_id: '104611'
  type: Marker
  safe_label: M_104611
- index: 29
  original_name: 右手左后
  original_id: '104613'
  type: Marker
  safe_label: M_104613
- index: 30
  original_name: 左手右后
  original_id: '104615'
  type: Marker
  safe_label: M_104615
- index: 31
  original_name: 右肩胛上区
  original_id: '104616'
  type: Marker
  safe_label: R_SCAP_SUP
- index: 32
  original_name: 肚子
  original_id: '104617'
  type: Marker
  safe_label: BELL
- index: 33
  original_name: 左三头肌中间
  original_id: '104618'
  type: Marker
  safe_label: M_104618
- index: 34
  original_name: 左手手腕
  original_id: '104621'
  type: Marker
  safe_label: L_WRA
- index: 35
  original_name: 右脚，小拇指旁
  original_id: '104622'
  type: Marker
  safe_label: M_104622
- index: 36
  original_name: 右肩胛下区
  original_id: '104623'
  type: Marker
  safe_label: R_SCAP_INF
- index: 37
  original_name: 额头上一点
  original_id: '104625'
  type: Marker
  safe_label: HEAD_FRONT
- index: 38
  original_name: 右脚脚后跟（左）
  original_id: '104626'
  type: Marker
  safe_label: R_HEE_02
- index: 39
  original_name: 右脚：脚背与小腿骨连接处
  original_id: '104627'
  type: Marker
  safe_label: R_ANK
- index: 40
  original_name: 右脚脚后跟（右）
  original_id: '104629'
  type: Marker
  safe_label: R_HEE_03
- index: 41
  original_name: 左手左后
  original_id: '104630'
  type: Marker
  safe_label: M_104630
- index: 42
  original_name: 左肩胛上区
  original_id: '104631'
  type: Marker
  safe_label: L_SCAP_SUP
- index: 43
  original_name: 左手左前
  original_id: '104632'
  type: Marker
  safe_label: M_104632
- index: 44
  original_name: 左手肘关节
  original_id: '104633'
  type: Marker
  safe_label: L_ELB
- index: 45
  original_name: 左髂嵴/PSIS区
  original_id: '104634'
  type: Marker
  safe_label: L_PSIS
- index: 46
  original_name: 左髂前上棘
  original_id: 104635+104644
  type: Marker
  safe_label: L_ASIS
- index: 47
  original_name: 左肩胛下区
  original_id: '104636'
  type: Marker
  safe_label: L_SCAP_INF
- index: 48
  original_name: 脊椎下区（略微偏左一点点）
  original_id: '104637'
  type: Marker
  safe_label: M_104637
- index: 49
  original_name: 左脚：脚背与小腿骨连接处
  original_id: '104638'
  type: Marker
  safe_label: L_ANK
