# @package _global_

defaults:
  - /config_specific_task/conf_fullbody_badminton_gmr
  - _self_

wandb:
  tags: ["fullbody", "badminton", "forehand_clear", "distill", "student_phase_ppo"]

experiment:
  resume_from: null
  auto_resume: false
  checkpoint_dir: checkpoints/distill_forehandclear_student_phase_ppo
  reset_std_on_resume: 1.0
  reset_lr_schedule_on_resume: true

  student_obs_filter:
    enabled: true
    drop_goal_lookahead: true
    keep_motion_phase: true
    require_goal_group: true
    require_motion_phase: true

  total_timesteps: 102400000
  lr: 1e-4
  max_grad_norm: 0.5

  ppo_config:
    num_steps: 80
    update_epochs: 1
    num_minibatches: 128
    gamma: 0.99
    gae_lambda: 0.95
    clip_eps: 0.2
    clip_eps_vf: 0.2
    init_std: 1.0
    learnable_std: true
    ent_coef: 0.0
    vf_coef: 0.5
