defaults:
  ForehandClear:
    expected_large_motion: false
  Backhand:
    expected_large_motion: false
  ForehandNetLift:
    expected_large_motion: true
  Smash:
    expected_large_motion: false

motions: {}
