#!/usr/bin/env bash
set -euo pipefail

# Source this file from the repository root:
#   source BadmintonMimic/configs/env.sh

BADMINTONMIMIC_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MUSCLEMIMIC_ROOT="$(cd "${BADMINTONMIMIC_ROOT}/.." && pwd)"

export BADMINTONMIMIC_ROOT
export MUSCLEMIMIC_ROOT

export MUSCLEMIMIC_AMASS_PATH="${BADMINTONMIMIC_ROOT}/data/amass_npz"
export AMASS_PATH="${MUSCLEMIMIC_AMASS_PATH}"

export MUSCLEMIMIC_CONVERTED_AMASS_PATH="${MUSCLEMIMIC_ROOT}/caches/AMASS"
export CONVERTED_AMASS_PATH="${MUSCLEMIMIC_CONVERTED_AMASS_PATH}"

export MUSCLEMIMIC_SMPL_MODEL_PATH="${MUSCLEMIMIC_ROOT}/smpl_models/smplh"
export SMPL_MODEL_PATH="${MUSCLEMIMIC_SMPL_MODEL_PATH}"

export MM_CUDA_COMPAT_ROOT="${MM_CUDA_COMPAT_ROOT:-/data3/yangfeiyang/WorkSpace/CUDA/12.4}"
export MM_CUDA_COMPAT_DIR="${MM_CUDA_COMPAT_ROOT}/compat"
if [[ -d "${MM_CUDA_COMPAT_DIR}" ]]; then
  export LD_LIBRARY_PATH="${MM_CUDA_COMPAT_DIR}:${LD_LIBRARY_PATH:-}"
fi

export XLA_PYTHON_CLIENT_PREALLOCATE="${XLA_PYTHON_CLIENT_PREALLOCATE:-false}"

mkdir -p "${MUSCLEMIMIC_AMASS_PATH}" "${MUSCLEMIMIC_CONVERTED_AMASS_PATH}"

echo "BADMINTONMIMIC_ROOT=${BADMINTONMIMIC_ROOT}"
echo "MUSCLEMIMIC_ROOT=${MUSCLEMIMIC_ROOT}"
echo "AMASS_PATH=${AMASS_PATH}"
echo "CONVERTED_AMASS_PATH=${CONVERTED_AMASS_PATH}"
echo "SMPL_MODEL_PATH=${SMPL_MODEL_PATH}"
echo "CUDA_COMPAT_DIR=${MM_CUDA_COMPAT_DIR}"
