"""Model-bound muscle physiology contracts and diagnostics."""

from musclemimic.physiology.anatomical_groups import (
    ANATOMICAL_TAXONOMY_SCHEMA_VERSION,
    DEFAULT_TRAINING_BEHAVIOR,
    FUNCTIONAL_SYNERGY_RELATIONSHIP,
    HARD_LINE_RELATIONSHIP,
    OBSERVATION_AGGREGATE_RELATIONSHIP,
    SOFT_COMPARTMENT_RELATIONSHIP,
    AnatomicalTaxonomy,
    build_intra_muscle_spec,
    load_anatomical_taxonomy,
    resolve_intra_muscle_reward_gate,
    taxonomy_fingerprint,
    validate_anatomical_taxonomy,
    validate_taxonomy_against_model,
)
from musclemimic.physiology.effective_excitation import (
    EFFECTIVE_EXCITATION_SEMANTICS,
    EFFECTIVE_EXCITATION_SOURCE,
    MUSCLE_ACTIVATION_SEMANTICS,
    MUSCLE_ACTIVATION_SOURCE,
    UNIT_MUSCLE_CTRLRANGE,
    MuscleChannelLayout,
    actuator_transmission_target,
    effective_excitation_clip_diagnostics,
    effective_mujoco_muscle_excitation,
    jax_effective_muscle_excitation,
    normalized_policy_action_to_unit_muscle_ctrl,
    resolve_muscle_channel_layout,
)
from musclemimic.physiology.effective_excitation import (
    ordered_body_activation as ordered_body_activation_from_layout,
)
from musclemimic.physiology.intra_muscle import (
    ExoImrMetrics,
    IntraMuscleMetrics,
    IntraMuscleSpec,
    exact_exo_imr,
    ordered_body_activation,
    robust_intra_muscle_consistency,
)
from musclemimic.physiology.synergy_binding import (
    SYNERGY_SCHEMA_HASH_FIELDS,
    SYNERGY_TAXONOMY_BINDING_SCHEMA_VERSION,
    assert_synergy_artifact_matches_taxonomy,
    assert_taxonomy_matches_ordered_muscles,
    ordered_muscle_schema_sha256,
    taxonomy_ordered_muscle_schema_hash,
)

__all__ = [
    "ANATOMICAL_TAXONOMY_SCHEMA_VERSION",
    "DEFAULT_TRAINING_BEHAVIOR",
    "EFFECTIVE_EXCITATION_SEMANTICS",
    "EFFECTIVE_EXCITATION_SOURCE",
    "FUNCTIONAL_SYNERGY_RELATIONSHIP",
    "HARD_LINE_RELATIONSHIP",
    "MUSCLE_ACTIVATION_SEMANTICS",
    "MUSCLE_ACTIVATION_SOURCE",
    "OBSERVATION_AGGREGATE_RELATIONSHIP",
    "SOFT_COMPARTMENT_RELATIONSHIP",
    "SYNERGY_SCHEMA_HASH_FIELDS",
    "SYNERGY_TAXONOMY_BINDING_SCHEMA_VERSION",
    "UNIT_MUSCLE_CTRLRANGE",
    "AnatomicalTaxonomy",
    "ExoImrMetrics",
    "IntraMuscleMetrics",
    "IntraMuscleSpec",
    "MuscleChannelLayout",
    "actuator_transmission_target",
    "assert_synergy_artifact_matches_taxonomy",
    "assert_taxonomy_matches_ordered_muscles",
    "build_intra_muscle_spec",
    "effective_excitation_clip_diagnostics",
    "effective_mujoco_muscle_excitation",
    "exact_exo_imr",
    "jax_effective_muscle_excitation",
    "load_anatomical_taxonomy",
    "normalized_policy_action_to_unit_muscle_ctrl",
    "ordered_body_activation",
    "ordered_body_activation_from_layout",
    "ordered_muscle_schema_sha256",
    "resolve_intra_muscle_reward_gate",
    "resolve_muscle_channel_layout",
    "robust_intra_muscle_consistency",
    "taxonomy_fingerprint",
    "taxonomy_ordered_muscle_schema_hash",
    "validate_anatomical_taxonomy",
    "validate_taxonomy_against_model",
]
