#!/usr/bin/env python3
"""Generate a per-action MyoFullBody tracking config (Stage 1 expert).

Emits a Hydra config under ``fullbody/config_specific_task/skill/`` that trains
a single-stroke tracking expert on the GMR-staged local trajectories produced
by ``stage_local_trajectories.py``. Optionally welds the racket to the right
hand so the expert learns the swing under the racket's added arm-tip inertia
(recommended: keeps Stage 1 kinematically consistent with the Stage 3 hitting
task, which is always racket-in-hand).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CONFIG_DIR = REPO_ROOT / "fullbody" / "config_specific_task" / "skill"


def _yaml_list(items: list[str], indent: int) -> str:
    pad = " " * indent
    return "\n".join(f'{pad}- "{item}"' for item in items)


def build_expert_config(
    action: str,
    train: list[str],
    val: list[str],
    *,
    num_envs: int = 256,
    total_timesteps: int = 20_480_000,
    target_fps: int = 100,
    disable_fingers: bool = True,
    racket: bool = False,
) -> str:
    tags = ["fullbody", "gmr", "badminton", "skill_expert", action]
    if racket:
        tags.append("racket")
    run_id = f"expert_{action}" + ("_racket" if racket else "")
    finger_flag = "false" if (racket or not disable_fingers) else "true"
    racket_block = ""
    if racket:
        racket_block = """
  # racket welded to the right hand: expert swings under the racket's arm-tip
  # inertia so the swing transfers to the Stage-3 hitting task
  skill_racket:
    enabled: true
    weld_solref: "0.005 1"
    weld_solimp: "0.9 0.99 0.0001"
"""
    return f"""# @package _global_
# Auto-generated by generate_expert_config.py — Stage 1 single-stroke expert.

defaults:
  - /conf_fullbody_gmr
  - _self_

wandb:
  project: "musclemimic"
  mode: "online"
  tags: {json.dumps(tags)}

experiment:
  training_action: {action}
  # readable checkpoint dir: datasets/{action}/training/checkpoints/{run_id}/
  run_id: {run_id}
  env_params:
    env_name: MjxMyoFullBody
    num_envs: {num_envs}
    disable_fingers: {finger_flag}

  total_timesteps: {total_timesteps}

  ppo_config:
    num_steps: 80
{racket_block}
  task_factory:
    params:
      amass_dataset_conf:
        dataset_group: null
        rel_dataset_path:
{_yaml_list(train, 10)}
        retargeting_method: gmr
        gmr_config:
          src_human: smplh
          target_fps: {target_fps}
          solver: daqp
          damping: 0.5
          offset_to_ground: false
          use_velocity_limit: false
          use_fitted_shape: true
          shape_fitting_iterations: 500

  validation:
    active: true
    deterministic: false
    num_steps: 500
    num_envs: 20
    num: 20
    amass_dataset_conf:
      dataset_group: null
      rel_dataset_path:
{_yaml_list(val, 8)}
      retargeting_method: gmr
      gmr_config:
        src_human: smplh
        target_fps: {target_fps}
        solver: daqp
        damping: 0.5
        offset_to_ground: false
        use_velocity_limit: false
        use_fitted_shape: true
        shape_fitting_iterations: 500
"""


def _read_list(path: Path) -> list[str]:
    return [ln.strip() for ln in path.read_text(encoding="utf-8").splitlines() if ln.strip()]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--action", required=True)
    parser.add_argument(
        "--manifest-dir",
        type=Path,
        default=None,
        help="dir with train_list.txt/val_list.txt (default datasets/<action>/manifests/skill_pipeline)",
    )
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--num-envs", type=int, default=256)
    parser.add_argument("--total-timesteps", type=int, default=20_480_000)
    parser.add_argument("--target-fps", type=int, default=100)
    parser.add_argument("--racket", action="store_true", help="weld racket to right hand")
    args = parser.parse_args()

    manifest_dir = (
        args.manifest_dir
        if args.manifest_dir is not None
        else REPO_ROOT / "datasets" / args.action / "manifests" / "skill_pipeline"
    )
    train = _read_list(manifest_dir / "train_list.txt")
    val = _read_list(manifest_dir / "val_list.txt")
    if not train or not val:
        raise ValueError(f"empty train/val manifest in {manifest_dir}")

    suffix = "_racket" if args.racket else ""
    out = args.out if args.out is not None else DEFAULT_CONFIG_DIR / f"conf_expert_{args.action}{suffix}.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        build_expert_config(
            args.action,
            train,
            val,
            num_envs=args.num_envs,
            total_timesteps=args.total_timesteps,
            target_fps=args.target_fps,
            racket=args.racket,
        )
    )
    print(str(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
