from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

import numpy as np


CHANNEL_NORMALIZATIONS = ("none", "unit_max", "unit_variance")

SESSION_METADATA_SCHEMA_VERSION = "emg_session_metadata_v2"
SESSION_METADATA_V2_OPTIONAL_PROVENANCE_FIELDS = frozenset(
    {
        "biological_subject_uid",
        "consent_protocol_id",
        "site_code",
        "device_model",
        "control_utility_version",
        "device_firmware",
        "sensor_serials",
        "placement_protocol_id",
        "electrode_coordinates",
        "electrode_orientations",
        "interelectrode_distance_mm",
        "video_reference",
    }
)
SESSION_METADATA_PROTECTED_OVERRIDE_FIELDS = frozenset(
    {
        "participant_id",
        "session_id",
        "channel_profile_id",
        "protocol_id",
        "handedness",
        "dominant_leg",
        "schema_version",
        "collection_date",
    }
)


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def merge_session_metadata_overrides(
    canonical: dict[str, Any],
    overrides: dict[str, Any] | None,
) -> dict[str, Any]:
    """Merge metadata while rejecting contradictory protected claims."""

    merged = dict(canonical)
    if not overrides:
        return merged
    if "collection_date" in overrides:
        raise ValueError(
            "session metadata overrides cannot provide collection_date; it is generated by the recorder"
        )
    for key in sorted(SESSION_METADATA_PROTECTED_OVERRIDE_FIELDS - {"collection_date"}):
        if key in overrides and overrides[key] != canonical[key]:
            raise ValueError(
                f"session metadata protected field {key!r} conflicts with the canonical value: "
                f"provided={overrides[key]!r}, canonical={canonical[key]!r}"
            )
    merged.update(
        {
            key: value
            for key, value in overrides.items()
            if key not in SESSION_METADATA_PROTECTED_OVERRIDE_FIELDS
        }
    )
    return merged


@dataclass(frozen=True)
class ChannelSpec:
    sensor_id: int
    side: Literal["left", "right", "midline", "unknown"]
    muscle_slug: str
    name_zh: str
    name_en: str
    abbreviation: str
    mvc_instruction_zh: str = "按标准抗阻姿势完成MVC并稳定保持3到5秒"

    def __post_init__(self) -> None:
        if not 1 <= self.sensor_id <= 16:
            raise ValueError(f"sensor_id must be in 1..16, got {self.sensor_id}")
        if not self.muscle_slug or not self.muscle_slug.replace("_", "").isalnum():
            raise ValueError(f"Unsafe muscle_slug: {self.muscle_slug!r}")


@dataclass(frozen=True)
class ChannelProfile:
    profile_id: str
    version: int
    description: str
    intended_handedness: Literal["right", "left", "either", "legacy_unknown"]
    channels: tuple[ChannelSpec, ...]

    def __post_init__(self) -> None:
        if not self.profile_id:
            raise ValueError("profile_id is required")
        if self.version < 1:
            raise ValueError("profile version must be >= 1")
        ids = [channel.sensor_id for channel in self.channels]
        if not ids or len(ids) != len(set(ids)):
            raise ValueError("Channel sensor IDs must be non-empty and unique")
        identities = [(channel.side, channel.muscle_slug) for channel in self.channels]
        if len(identities) != len(set(identities)):
            raise ValueError("Duplicate side+muscle_slug identities are not allowed")

    @property
    def channel_ids(self) -> tuple[int, ...]:
        return tuple(channel.sensor_id for channel in self.channels)

    def validate_handedness(self, handedness: str) -> None:
        if handedness not in {"right", "left"}:
            raise ValueError("handedness must be explicitly 'right' or 'left'")
        if self.intended_handedness in {"right", "left"} and handedness != self.intended_handedness:
            raise ValueError(
                f"Profile {self.profile_id} is for {self.intended_handedness}-handed athletes; "
                f"refusing to silently mirror a {handedness}-handed participant"
            )

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["channels"] = list(payload["channels"])
        return payload


@dataclass(frozen=True)
class ActionSpec:
    action_id: str
    display_name_zh: str
    category: Literal["primitive", "complete"]
    duration_s: float
    baseline_s: float
    cue_s: float
    post_s: float
    target_valid_trials: int
    blocks: int
    rest_between_trials_s: float
    rest_between_blocks_s: float
    instruction_zh: str
    includes_racket: bool
    includes_shuttle: bool
    includes_jump: bool
    requires_racket_contact: bool
    requires_foot_contact: bool

    def __post_init__(self) -> None:
        timing_values = (
            self.duration_s,
            self.baseline_s,
            self.cue_s,
            self.post_s,
            self.rest_between_trials_s,
            self.rest_between_blocks_s,
        )
        if not self.action_id or not all(np.isfinite(value) for value in timing_values) or self.duration_s <= 0:
            raise ValueError("action_id and positive duration_s are required")
        if min(
            self.baseline_s,
            self.cue_s,
            self.post_s,
            self.rest_between_trials_s,
            self.rest_between_blocks_s,
        ) < 0:
            raise ValueError("Action timing values cannot be negative")
        if self.target_valid_trials < 1 or self.blocks < 1:
            raise ValueError("target_valid_trials and blocks must be >= 1")

    @property
    def total_recording_s(self) -> float:
        return self.baseline_s + self.cue_s + self.duration_s + self.post_s


@dataclass(frozen=True)
class ActionProtocol:
    protocol_id: str
    version: int
    description: str
    actions: tuple[ActionSpec, ...]

    def __post_init__(self) -> None:
        ids = [action.action_id for action in self.actions]
        if not self.protocol_id or len(ids) != len(set(ids)):
            raise ValueError("protocol_id is required and action IDs must be unique")

    def action(self, action_id: str) -> ActionSpec:
        for action in self.actions:
            if action.action_id == action_id:
                return action
        raise KeyError(f"Unknown action {action_id!r} in {self.protocol_id}")

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["actions"] = list(payload["actions"])
        return payload


@dataclass(frozen=True)
class TrignoConfig:
    host: str = "127.0.0.1"
    command_port: int = 50040
    emg_port: int = 50041
    sample_rate_hz: float = 2000.0
    total_stream_channels: int = 16
    bytes_per_float: int = 4
    samples_per_read: int = 200
    stream_scale_to_mV: float = 1000.0
    connect_timeout_s: float = 10.0
    receive_timeout_s: float = 10.0

    def __post_init__(self) -> None:
        if self.sample_rate_hz <= 0 or self.total_stream_channels != 16:
            raise ValueError("Trigno stream requires a positive sample rate and 16 stream channels")
        if self.bytes_per_float != 4 or self.stream_scale_to_mV <= 0:
            raise ValueError("Trigno float width and stream scale must be positive and explicit")


@dataclass
class RecordResult:
    emg_mV: np.ndarray
    fs_hz: float
    stream_channel_ids: np.ndarray
    expected_samples: int
    received_samples: int
    dropped_samples: int
    start_time: str
    stop_time: str
    interrupted: bool = False
    receive_error: str | None = None

    @property
    def incomplete(self) -> bool:
        return self.received_samples != self.expected_samples

    @property
    def actual_duration_s(self) -> float:
        return self.received_samples / self.fs_hz

    @property
    def time_s(self) -> np.ndarray:
        return np.arange(self.received_samples, dtype=np.float64) / self.fs_hz

    @property
    def sample_index(self) -> np.ndarray:
        return np.arange(self.received_samples, dtype=np.int64)


@dataclass(frozen=True)
class ProcessingConfig:
    sample_rate_hz: float = 2000.0
    bandpass_low_hz: float = 30.0
    bandpass_high_hz: float = 300.0
    filter_order: int = 4
    envelope_lowpass_hz: float = 4.0
    mvc_envelope_lowpass_hz: float = 4.0
    notch_hz: float | None = 50.0
    notch_bandwidth_hz: float = 5.0
    notch_quality_factor: float | None = None
    zero_phase: bool = True
    minimum_duration_s: float = 0.5
    edge_guard_s: float = 0.25
    missing_value_policy: Literal["interpolate", "raise"] = "interpolate"
    max_missing_fraction: float = 0.01
    max_interpolation_gap_s: float = 0.1
    outlier_policy: Literal["interpolate", "report", "raise"] = "interpolate"
    outlier_mad_threshold: float = 20.0
    max_outlier_run_samples: int = 3
    powerline_ratio_warn: float = 0.2
    max_notch_removed_variance_fraction: float = 0.8
    minimum_filtered_rms_mV: float = 0.001
    normalization: Literal["mvc", "dynamic_p95", "none"] = "mvc"

    def __post_init__(self) -> None:
        nyquist = self.sample_rate_hz / 2.0
        if self.sample_rate_hz <= 0 or self.filter_order < 1:
            raise ValueError("sample rate and filter order must be positive")
        if not 0 < self.bandpass_low_hz < self.bandpass_high_hz < nyquist:
            raise ValueError("Band-pass cutoffs must satisfy 0 < low < high < Nyquist")
        if not 0 < self.envelope_lowpass_hz < nyquist:
            raise ValueError("Envelope cutoff must be below Nyquist")
        if self.notch_hz is not None and not 0 < self.notch_hz < nyquist:
            raise ValueError("Notch frequency must be below Nyquist")
        if self.notch_bandwidth_hz <= 0:
            raise ValueError("Notch bandwidth must be positive")
        if self.notch_quality_factor is not None and self.notch_quality_factor <= 0:
            raise ValueError("Notch quality factor must be positive when provided")
        if self.minimum_duration_s <= 0 or self.edge_guard_s < 0:
            raise ValueError("Minimum duration must be positive and edge guard cannot be negative")
        if not 0 <= self.max_missing_fraction <= 1 or self.max_interpolation_gap_s < 0:
            raise ValueError("Missing-value limits are invalid")
        if self.outlier_mad_threshold <= 0 or self.max_outlier_run_samples < 0:
            raise ValueError("Outlier limits must be positive")
        if not 0 <= self.powerline_ratio_warn <= 1:
            raise ValueError("Power-line warning ratio must be in [0, 1]")
        if not 0 <= self.max_notch_removed_variance_fraction <= 1:
            raise ValueError("Notch removed-variance limit must be in [0, 1]")
        if self.minimum_filtered_rms_mV < 0:
            raise ValueError("Minimum filtered RMS cannot be negative")

    @property
    def effective_notch_quality_factor(self) -> float | None:
        if self.notch_hz is None:
            return None
        if self.notch_quality_factor is not None:
            return self.notch_quality_factor
        return self.notch_hz / self.notch_bandwidth_hz

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class SessionMetadata:
    participant_id: str
    session_id: str
    channel_profile_id: str
    protocol_id: str
    handedness: Literal["right", "left"]
    schema_version: str = SESSION_METADATA_SCHEMA_VERSION
    dominant_leg: str = "unknown"
    biological_subject_uid: str | None = None
    consent_protocol_id: str | None = None
    site_code: str | None = None
    device_model: str | None = None
    control_utility_version: str | None = None
    device_firmware: str | None = None
    sensor_serials: dict[str, str] | None = None
    placement_protocol_id: str | None = None
    electrode_coordinates: dict[str, list[float]] | None = None
    electrode_orientations: dict[str, str] | None = None
    interelectrode_distance_mm: float | dict[str, float] | None = None
    video_reference: str | None = None
    age_years: float | None = None
    sex: str = "not_reported"
    height_cm: float | None = None
    mass_kg: float | None = None
    training_years: float | None = None
    competition_level: str = "not_reported"
    recent_injuries: str = "not_reported"
    racket_mass_g: float | None = None
    grip_size: str = "not_reported"
    string_tension_lb: float | None = None
    operator: str = "not_reported"
    electrode_notes: str = ""
    collection_date: str = field(default_factory=utc_now_iso)

    def __post_init__(self) -> None:
        if self.schema_version != SESSION_METADATA_SCHEMA_VERSION:
            raise ValueError(
                f"Session metadata schema must be {SESSION_METADATA_SCHEMA_VERSION!r}, "
                f"got {self.schema_version!r}"
            )
        if self.sensor_serials is not None:
            if not isinstance(self.sensor_serials, dict):
                raise ValueError("sensor_serials must be an object mapping sensor IDs to serials")
            invalid = [
                key
                for key, value in self.sensor_serials.items()
                if not str(key).isdigit()
                or not 1 <= int(str(key)) <= 16
                or not str(value).strip()
            ]
            if invalid:
                raise ValueError(f"Invalid sensor_serials entries for keys: {invalid}")
        if self.electrode_coordinates is not None:
            if not isinstance(self.electrode_coordinates, dict):
                raise ValueError("electrode_coordinates must map sensor IDs to numeric coordinates")
            for key, coordinates in self.electrode_coordinates.items():
                values = np.asarray(coordinates, dtype=np.float64)
                if (
                    not str(key).isdigit()
                    or not 1 <= int(str(key)) <= 16
                    or values.ndim != 1
                    or values.size not in {2, 3}
                    or not np.all(np.isfinite(values))
                ):
                    raise ValueError(f"Invalid electrode_coordinates entry for sensor {key!r}")
        if self.electrode_orientations is not None:
            if not isinstance(self.electrode_orientations, dict):
                raise ValueError("electrode_orientations must map sensor IDs to descriptions")
            invalid = [
                key
                for key, value in self.electrode_orientations.items()
                if not str(key).isdigit()
                or not 1 <= int(str(key)) <= 16
                or not str(value).strip()
            ]
            if invalid:
                raise ValueError(f"Invalid electrode_orientations entries for keys: {invalid}")
        distances = self.interelectrode_distance_mm
        if isinstance(distances, dict):
            invalid = [
                key
                for key, value in distances.items()
                if not str(key).isdigit()
                or not 1 <= int(str(key)) <= 16
                or isinstance(value, bool)
                or not isinstance(value, (int, float))
                or not np.isfinite(value)
                or value <= 0
            ]
            if invalid:
                raise ValueError(f"Invalid interelectrode_distance_mm entries for keys: {invalid}")
        elif distances is not None:
            if (
                isinstance(distances, bool)
                or not isinstance(distances, (int, float))
                or not np.isfinite(distances)
                or distances <= 0
            ):
                raise ValueError("interelectrode_distance_mm must be finite and positive")

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class TrialMetadata:
    participant_id: str
    session_id: str
    trial_id: str
    trial_index: int
    action_id: str
    protocol_id: str
    protocol_version: int
    channel_profile_id: str
    channel_profile_version: int
    channel_profile_snapshot: dict[str, Any]
    handedness: str
    dominant_leg: str
    sample_rate_hz: float
    requested_duration_s: float
    actual_duration_s: float
    expected_samples: int
    received_samples: int
    dropped_samples: int
    start_time: str
    valid_for_analysis: bool
    error_labels: list[str]
    operator_notes: str
    racket: dict[str, Any]
    includes_shuttle: bool
    sync_method: str
    software_version: str
    git_commit_hash: str | None
    qc_pass: bool
    interrupted: bool = False
    receive_error: str | None = None
    post_trial_rest: dict[str, Any] | None = None

    def validate_shape(self, emg: np.ndarray) -> None:
        expected_channels = len(self.channel_profile_snapshot["channels"])
        if emg.ndim != 2 or emg.shape[1] != expected_channels:
            raise ValueError(
                f"EMG columns {emg.shape if hasattr(emg, 'shape') else '?'} do not match "
                f"profile channel count {expected_channels}"
            )
        if emg.shape[0] != self.received_samples:
            raise ValueError("EMG row count does not match received_samples")

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def path_jsonable(value: Path | str) -> str:
    return str(value)
