pelvis:
  myo_body: pelvis
  weight: 1.0
thorax:
  myo_body: torso
  weight: 1.0
head:
  myo_body: head
  weight: 0.5
left_hip:
  myo_body: femur_l
  weight: 0.8
left_knee:
  myo_body: tibia_l
  weight: 0.8
left_ankle:
  myo_body: talus_l
  weight: 1.0
left_toe:
  myo_site: toe_l
  weight: 1.0
left_heel:
  myo_site: heel_l
  weight: 1.0
right_hip:
  myo_body: femur_r
  weight: 0.8
right_knee:
  myo_body: tibia_r
  weight: 0.8
right_ankle:
  myo_body: talus_r
  weight: 1.0
right_toe:
  myo_site: toe_r
  weight: 1.0
right_heel:
  myo_site: heel_r
  weight: 1.0
left_shoulder:
  myo_body: humerus_l
  weight: 0.4
left_elbow:
  myo_body: ulna_l
  weight: 0.35
left_wrist:
  myo_body: ulna_l
  weight: 0.2
right_shoulder:
  myo_body: humerus_r
  weight: 0.4
right_elbow:
  myo_body: ulna_r
  weight: 0.35
right_wrist:
  myo_body: ulna_r
  weight: 0.2
